name = "basic_auth"
description = "Basic authentication component, for verifying RPO Falcon signatures."
version = "0.1.0"
supported-types = ["RegularAccountUpdatableCode", "RegularAccountImmutableCode", "FungibleFaucet", "NonFungibleFaucet"]

[storage]
[[storage.slots]]
name = "miden::standards::auth::rpo_falcon512::public_key"
description = "Falcon public key"
type = "miden::standards::auth::rpo_falcon512::pub_key"
