name: Build
on:
  push:
    branches: [main, next]
  pull_request:
    types: [opened, reopened, synchronize]
permissions:
  contents: read

jobs:
  build:
    name: Build Client and CLI on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install Rust toolchain
        run: rustup update --no-self-update
      - name: Add Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: make - build
        run: make build
  build-wasm:
    name: Build Client on ubuntu-latest for wasm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install Rust toolchain
        run: rustup update --no-self-update
      - name: Add wasm32-unknown-unknown target
        run: rustup target add wasm32-unknown-unknown
      - name: Add Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: make - build-wasm
        run: make build-wasm

  build-react-sdk:
    name: Build React SDK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: |
          cd ./crates/react-sdk
          yarn install
      - name: Build React SDK
        run: make build-react-sdk
