name: Lint
permissions:
  contents: read
on:
  push:
    branches: [main, next]
  pull_request:

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

env:
  CARGO_PROFILE_DEV_DEBUG: 0
  RUST_CACHE_KEY: rust-cache-2026.02.18

jobs:
  unused_deps:
    name: Check for unused dependencies
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: machete
        uses: bnjbvr/cargo-machete@main

  typos:
    name: Spellcheck
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - uses: taiki-e/install-action@v2
        with:
          tool: typos@1.42.0
      - run: make typos-check

  toml:
    name: Toml formatting
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - uses: taiki-e/install-action@v2
        with:
          tool: taplo-cli@0.10.0
      - run: make toml-check

  eslint:
    name: Typescript eslint checks
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: make rust-client-ts-lint

  react-sdk-lint:
    name: React SDK lint and typecheck
    runs-on: ubuntu-24.04
    needs: [wasm-bindgen-types]
    steps:
      - uses: actions/checkout@v6
      - name: Fetch web client dist
        uses: actions/download-artifact@v4
        with:
          name: web-client-artifacts
          path: ./crates/web-client/dist
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Check React SDK version sync
        run: node scripts/check-react-sdk-sync.js
      - name: Install dependencies
        run: ./scripts/retry-yarn-install.sh packages/react-sdk
      - name: Run lint
        run: make react-sdk-lint
      - name: Run typecheck
        run: cd ./packages/react-sdk && yarn typecheck

  clippy:
    name: Clippy
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust with clippy
        run: |
          rustup update --no-self-update
          rustup component add clippy
      - name: Add Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: rust-debug
          prefix-key: ${{ env.RUST_CACHE_KEY }}
          save-if: ${{ github.ref == 'refs/heads/next' }}
      - name: make - clippy
        run: make clippy

  clippy-wasm:
    name: Clippy WASM
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust with clippy
        run: |
          rustup update --no-self-update
          rustup target add wasm32-unknown-unknown
          rustup component add clippy
      - name: Add Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: rust-wasm
          prefix-key: ${{ env.RUST_CACHE_KEY }}
          save-if: false
      - name: make - clippy-wasm
        run: make clippy-wasm

  format:
    name: Format check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust with rustfmt
        run: |
          rustup update --no-self-update nightly
          rustup +nightly component add rustfmt
      - name: Install prettier
        run: yarn install
      - name: make - format-check
        run: make format-check

  wasm-bindgen-types:
    name: Wasm bindgen types
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: |
            crates/web-client/yarn.lock
            crates/idxdb-store/src/yarn.lock
      - name: Install Rust with wasm target
        run: |
          rustup update --no-self-update
          rustup target add wasm32-unknown-unknown
      - name: Add Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: rust-wasm
          prefix-key: ${{ env.RUST_CACHE_KEY }}
          save-if: false
      - name: Install dependencies
        working-directory: crates/web-client
        run: yarn install --frozen-lockfile
      - name: Build web client
        working-directory: crates/web-client
        run: yarn build
      - name: Check bindgen type coverage
        working-directory: crates/web-client
        run: yarn check:wasm-types
      - name: Upload web client dist
        uses: actions/upload-artifact@v4
        with:
          name: web-client-artifacts
          path: ./crates/web-client/dist

  rustdocs:
    name: Build rust documentation
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust
        run: rustup update --no-self-update
      - name: Add Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: rust-nightly-release # TODO: remove once https://github.com/rust-lang/rust/pull/150055 gets stabilized.
          prefix-key: ${{ env.RUST_CACHE_KEY }}
          save-if: ${{ github.ref == 'refs/heads/next' }}
      - name: make - doc
        run: make doc
