name: Dry Run Publish Rust Crates

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-24.04
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Check out code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Cleanup large tools for build space
        uses: ./.github/actions/cleanup-runner

      - name: Update Rust toolchain
        run: |
          rustup update --no-self-update

      - name: Dry run - publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: |
          cargo publish --workspace --exclude miden-client-web --exclude miden-idxdb-store --dry-run
          cd crates/idxdb-store
          cargo publish --dry-run
          cd ../web-client
          cargo publish --dry-run
